### PR TITLE
Split FromGlibPtr trait

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/gdk/issues/136

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
👍 Just waiting for CIs now...

**Comment by EPashkin** [comment]
It can compiles only on last PR

**Comment by EPashkin** [comment]
Namely `Gdk`, as `Gtk` unaffected.

**Comment by GuillaumeGomez** [comment]
So merging everything and we'll see at the end I guess. Thanks then!

**Pull request merged**
