### PR TITLE
Improve docs.rs documentation

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Part of gtk-rs/gir#820.

cc @EPashkin @sdroege

### CODE REVIEW

**Comment by EPashkin** [comment]
@GuillaumeGomez thanks

**Comment by GuillaumeGomez** [comment]
```
error: process didn't exit successfully: `/home/travis/build/gtk-rs/glib/target/debug/deps/glib-127833c13230d805` (signal: 11, SIGSEGV: invalid memory reference)
```

O.O

Is it "expected"?

**Comment by sdroege** [comment]
Nice can you reproduce it?

**Comment by GuillaumeGomez** [comment]
Didn't try yet. Will check on my linux tomorrow.

**Comment by sdroege** [comment]
Well, I can't. Only found a different issue :)

**Comment by GuillaumeGomez** [comment]
Dark magic is back!

**Comment by GuillaumeGomez** [comment]
Can't reproduce it either...

**Comment by EPashkin** [comment]
And error is gone after restart

**Pull request merged**
