### PR TITLE
Use g_type_register_static_simple() instead of g_type_register_static…

### PR DESCRIPTION
**Pull request by sdroege**
…() for simplicity

----

CC @GuillaumeGomez @EPashkin

### CODE REVIEW

**Comment by sdroege** [comment]
@GuillaumeGomez The clone tests are failing somehow, which is unrelated to my changes: https://travis-ci.org/github/gtk-rs/glib/jobs/703869975

Any guesses?

**Comment by GuillaumeGomez** [comment]
Let's check once if it fails again. But I wonder if the problem doesn't come from the compiler error output...

**Comment by sdroege** [comment]
> Let's check once if it fails again. But I wonder if the problem doesn't come from the compiler error output...

Oh maybe the compiler warning broke it

**Comment by sdroege** [comment]
That was it apparently. Now just the mac runner exploded :man_shrugging:

**Pull request merged**
