### PR TITLE
Use ptr::NonNull for Boxed/Shared wrappers

### PR DESCRIPTION
**Pull request by sdroege**
This allows the compiler to optimize better, and in our case these
pointers are guaranteed to be not NULL.

Requires Rust 1.25. We might want to do the same for Stash maybe, or even the translation traits. But that's far more intrusive.

### CODE REVIEW

**Comment by EPashkin** [comment]
Very good, but IMHO better wait for stable 1.26 or even 1.27

**Comment by sdroege** [comment]
You mean to prevent another annoyance like with the callback guards?

**Comment by EPashkin** [comment]
Yes

**Comment by sdroege** [comment]
Ok, not that important in any case :) I updated GStreamer to use it already though

**Comment by GuillaumeGomez** [comment]
Then I'll merge it as well (you should have remind me this one! ><).

**Pull request merged**
