### PR TITLE
Implement pushing/popping a thread default main context in a panic-sa…

### PR DESCRIPTION
**Pull request by sdroege**
…fe way

Not sure about the name of the struct. And maybe we need to somehow prevent it from implementing `Send`.

### CODE REVIEW

**Comment by tmiasko** [comment]
What exactly could panic here? 

This approach still allows one to cross the lifetimes of different contexts.
Using a method that accepts a closure would eliminate the issue (as long one
does not call push / pop, manually). Maybe something alone the lines of:

```rust
ctx.with_thread_default(|| {
  ...
});

with_thread_default_context(ctx, || {
  ...  
});

thread_default(ctx, || {
  ...  
});
```

**Comment by sdroege** [comment]
> What exactly could panic here?

If something between push and pop panics, pop would never happen

You're right though, it's possible to mess up the order here still and it would ideally have to be done with a closure like you suggest. Thanks!

**Comment by sdroege** [comment]
The question then is whether we want that or if it's too annoying to use. Opinions?

**Comment by sdroege** [comment]
Closing in favour of https://github.com/gtk-rs/glib/pull/319

**Pull request closed without merging**
