### PR TITLE
Dox

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Needed by https://github.com/gtk-rs/gio/pull/57

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
@EPashkin: Do you know why `uuid_string_is_valid` and `uuid_string_random` aren't generated anymore?

**Comment by EPashkin** [comment]
#231 was not rebased to master and moved gir-files back

**Comment by EPashkin** [comment]
Seems really @sdroege just erroneously committed submodule reverse

**Comment by sdroege** [comment]
So it seems. Sorry!

**Comment by EPashkin** [comment]
No problem, as we find it in almost next PR :wink:

**Comment by GuillaumeGomez** [comment]
They're back now. :)

**Comment by EPashkin** [comment]
👍

**Comment by GuillaumeGomez** [comment]
Great, let's just wait for CI then.

**Pull request merged**
