### PR TITLE
Add wrapper macros and extend glib::translate

### PR DESCRIPTION
**Pull request by gkoz**

### CODE REVIEW

**Comment by gkoz** [comment]
Just putting this out there.
Don't merge yet, I'd like to publish the crates first.

**Comment by gkoz** [comment]
Modified the macro syntax and added object types support. Examples;

```rust

glib_wrapper! {
    /// Text buffer iterator
    pub struct TextIter(Boxed<ffi::GtkTextIter>);

    match fn {
        copy => |ptr| ffi::gtk_text_iter_copy(ptr),
        free => |ptr| ffi::gtk_text_iter_free(ptr),
    }
}

glib_wrapper!{
    /// Object representing an input device
    pub struct Device(Object<ffi::GdkDevice>);

    match fn {
        get_type => || ffi::gdk_device_get_type(),
    }
}
```

**Comment by gkoz** [comment]
Might also add some syntax for `Upcast` impls.

**Comment by GuillaumeGomez** [comment]
The code is getting more and more difficult to understand but its usage is improving quite a lot. However, with this approach, we have to "redeclare" all the specialized method, right ?

**Comment by gkoz** [comment]
You had to put these in somehow before as well but it was more boilerplate:
```rust
impl types::StaticType for Device {
    fn static_type() -> types::Type { unsafe { from_glib(ffi::gdk_device_get_type()) } }
}
```
Now the `glib` crate is taking care of most gory details. It has to be macros because the newtypes must be defined in the crates that implement them.

**Comment by gkoz** [comment]
Expanded the object wrapper macro to support upcasts.

**Comment by gkoz** [comment]
This can be merged now if there are no objections.

**Comment by GuillaumeGomez** [comment]
There is no such things. Really nice work, thanks !

**Pull request merged**
