### PR TITLE
Rewrite string consts

### PR DESCRIPTION
**Pull request by EPashkin**
Preparation for apply https://github.com/gtk-rs/gir/pull/339
cc @GuillaumeGomez, @sdroege

### CODE REVIEW

**Comment by EPashkin** [comment]
This will fail

**Comment by GuillaumeGomez** [comment]
Hum... The output isn't very readable but otherwise it's a great idea! 👍

**Comment by EPashkin** [comment]
As only glib affected we can always change this do direct string,

**Comment by EPashkin** [comment]
@GuillaumeGomez merge this please, I add to sys.

**Comment by GuillaumeGomez** [comment]
Sure.

**Pull request merged**
