### PR TITLE
make get_real_name return OsString

### PR DESCRIPTION
**Pull request by andy128k**
Fix https://github.com/gtk-rs/glib/issues/346

### CODE REVIEW

**Comment by EPashkin** [comment]
Please change first comment to "Fix #346" to auto-close issue,
and change `get_user_name` too.

**Comment by sdroege** [comment]
Looks good apart from that, thanks!

**Comment by EPashkin** [comment]
@andy128k Thanks.
@GuillaumeGomez 👍 and CI passed

**Comment by GuillaumeGomez** [comment]
Thanks! :)

**Pull request merged**
