### PR TITLE
Allow FnOnce for MainContext::invoke()

### PR DESCRIPTION
**Pull request by sdroege**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
And there even is a test! :+1:

**Comment by sdroege** [comment]
And it even works on Windows

**Comment by EPashkin** [comment]
@sdroege Big thanks, this is great improvement.
👍

**Comment by GuillaumeGomez** [comment]
That's so crazy that I decided on my own to click on "Merge pull request"! I can't even handle this much crazyness (and thanks again btw! :wink: )!

**Pull request merged**
