### PR TITLE
Add signal_handler_*block()

### LINKED ISSUE #133: Add g_signal_handler_block/unblock
Needed for a project I'm working on. Should be simple to implement I think, so I'm willing to do it as I did for `signal_stop_emission*()`.

### PR DESCRIPTION
**Pull request by Susurrus**
Closes #133. Tested working correctly with my Gattii project.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
:+1:

**Comment by gkoz** [comment]
Looks all right. Mind adding `signal_handler_disconnect` as well?

**Comment by Susurrus** [comment]
I'm not planning on adding `_disconnect`. It's not necessary for my application and I'd rather focus my efforts there right now.

**Comment by gkoz** [comment]
Thanks for the PR.

**Pull request merged**
