### PR TITLE
0.9.3 release

### PR DESCRIPTION
**Pull request by sdroege**
CC @GuillaumeGomez @EPashkin

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Please push the version number on master as well and then pick the commit from there.

**Comment by sdroege** [comment]
> Please push the version number on master as well and then pick the commit from there.

No because that commit has `[ci skip]` like we did in the past :) See https://github.com/gtk-rs/glib/pull/595

**Comment by GuillaumeGomez** [comment]
Indeed, my bad.

**Comment by GuillaumeGomez** [comment]
:+1:

**Pull request merged**
