### PR TITLE
Various signal subclass improvements

### PR DESCRIPTION
**Pull request by sdroege**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
👍

**Comment by EPashkin** [comment]
👍 Thanks

**Comment by GuillaumeGomez** [comment]
```
error[E0433]: failed to resolve: could not find `unix` in `os`
 --> src\source.rs:8:14
  |
8 | use std::os::unix::io::RawFd;
  |              ^^^^ could not find `unix` in `os`
error: Compilation failed, aborting rustdoc
```

**Comment by EPashkin** [comment]
👍

**Comment by sdroege** [comment]
> `` error[E0433]: failed to resolve: could not find `unix` in `os` ``

Should be fixed now, let's see

**Comment by sdroege** [comment]
Yeah that part is fixed, now we only have the general CI setup being broken left (and the examples PR must be merged).

**Comment by sdroege** [comment]
Merging then, let's figure out the CI in another PR (and on some parts @EPashkin is already working).

**Pull request merged**
