### PR TITLE
Add API for implementing GObject interfaces generically

### PR DESCRIPTION
**Pull request by sdroege**
Fixes https://github.com/gtk-rs/glib/issues/408

### CODE REVIEW

**Comment by sdroege** [comment]
Usage can be found in
* https://gitlab.freedesktop.org/slomo/gstreamer-rs/commit/f341973d736ce037f658a2e2720a68c9b20b7480
* https://gitlab.freedesktop.org/slomo/gst-plugins-rs/commit/41f12097072fa1b7fd491f081e4a004730912c44

CC @fengalin

**Comment by EPashkin** [comment]
@sdroege `let data = &mut *data.as_mut();` why not just `let data = data.as_mut();` ?

**Comment by sdroege** [comment]
> @sdroege `let data = &mut *data.as_mut();` why not just `let data = data.as_mut();` ?

Leftover from previous versions. Changed that, thanks :)

Apart from that the change looks fine to you, @EPashkin? I mean the parts especially

**Comment by EPashkin** [comment]
Yes, all other looks good for me

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
