### PR TITLE
Test with gtk3.22.30

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/examples/pull/173

cc @GuillaumeGomez, @sdroege

### CODE REVIEW

**Comment by EPashkin** [comment]
@GuillaumeGomez Please restart 2 failed jobs on travis

**Comment by GuillaumeGomez** [comment]
I restarted them.

**Comment by EPashkin** [comment]
@GuillaumeGomez Thanks, and CI passed now

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
