### PR TITLE
Add struct Boxed -- a building block for binding boxed types

### PR DESCRIPTION
**Pull request by gkoz**

### CODE REVIEW

**Comment by gkoz** [comment]
@GuillaumeGomez let's not merge this for now.

**Comment by GuillaumeGomez** [comment]
Just tell me when your work is done then (and thanks for the PR ! ^^).

**Comment by gkoz** [comment]
kay I'm going to merge this?

**Comment by GuillaumeGomez** [comment]
Please do. ^^

**Pull request merged**
