### PR TITLE
Add missing #[doc(hidden)]

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
cc @EPashkin @sdroege

### CODE REVIEW

**Comment by EPashkin** [comment]
👍

**Comment by sdroege** [comment]
```
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libffi', required by 'gobject-2.0', not found
```

Travis is unhappy, but only on some configurations. Not sure what the problem there is, `libglib2.0-dev` should pull in `libffi-dev` already.

----

Otherwise looks good to me. Do you have an automated way of finding these, some script?

**Comment by EPashkin** [comment]
This seems osx brew packaging problem.
It was not listed as dependency and removed https://travis-ci.org/gtk-rs/glib/jobs/502818085#L1571

**Comment by EPashkin** [comment]
@GuillaumeGomez, @sdroege Can we merge this and fix osx in separate PRs?
I plan finish my gtk's PR today and better rebase it to new master to solve merge conflicts.

**Comment by EPashkin** [comment]
Oh, sorry, I was sure that #doc[hidden] added to gtk.

**Comment by sdroege** [comment]
> This seems osx brew packaging problem.
> It was not listed as dependency and removed https://travis-ci.org/gtk-rs/glib/jobs/502818085#L1571

libffi is a hard dependency for glib, so that's indeed a brew bug then.

**Comment by sdroege** [comment]
> @GuillaumeGomez, @sdroege Can we merge this and fix osx in separate PRs?

Sure

**Comment by GuillaumeGomez** [comment]
Then please merge @sdroege :)

**Pull request merged**
