### PR TITLE
Cast trampolines before transmuting

### PR DESCRIPTION
**Pull request by EPashkin**
Fix warning introduced https://github.com/rust-lang/rust/issues/19925
See https://github.com/gtk-rs/gtk/issues/278

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Good for me. Thanks @EPashkin!

**Comment by gkoz** [comment]
We can do better. I consider `as usize` the last resort but here the `fn`s can actually match the `GSourceFunc` signature.

**Comment by EPashkin** [comment]
Then we need at minimum these changes:
1) make trampolines `unsafe`,
2) change trampolines `func` to `gpointer` and transmute it back
3) change parameter on call ffi function to `Some(trampoline)`
```
unsafe extern "C" fn trampoline(func: gpointer) -> gboolean {
    let func: &RefCell<Box<FnMut() -> Continue + 'static>> = transmute(func);
    let _guard = CallbackGuard::new();
    (&mut *func.borrow_mut())().to_glib()
}

pub fn idle_add<F>(func: F) -> u32
where F: FnMut() -> Continue + Send + 'static {
    unsafe {
        glib_ffi::g_idle_add_full(glib_ffi::G_PRIORITY_DEFAULT_IDLE, Some(trampoline),
            into_raw(func), Some(destroy_closure))
    }
}
```

**Comment by EPashkin** [comment]
I don't like part about `unsafe`

**Comment by gkoz** [comment]
Yes, something along those lines. Typically the trampolines do something unsafe (at least transmute the argument) so there is some justification for their being `unsafe` overall.

Here had the function not been `unsafe` I'd probably still put the meat of it in an `unsafe` block because letting `func` escape that block doesn't make much sense to me.
```rust
    let _guard = CallbackGuard::new();
    unsafe {
        let func: &RefCell<Box<FnMut() -> Continue + 'static>> = transmute(func);
        (&mut *func.borrow_mut())().to_glib()
    }
```

Finally, keeping the `&RefCell<Box<FnMut() -> Continue + 'static>>` bit in the signature is just as unsafe but in a more silent way.

**Comment by EPashkin** [comment]
On nightly build safe trampolines don't convert automatically to unsafe:
```
source.rs:74:75: 74:85 error: mismatched types:
 expected `unsafe extern "C" fn(*mut libc::c_void) -> i32`,
    found `extern "C" fn(*mut libc::c_void) -> i32 {source::trampoline}`
(expected unsafe fn,
    found normal fn) [E0308]
source.rs:74         glib_ffi::g_idle_add_full(glib_ffi::G_PRIORITY_DEFAULT_IDLE, Some(trampoline),
                                                                                       ^~~~~~~~~~
source.rs:74:75: 74:85 help: run `rustc --explain E0308` to see a detailed explanation
```

**Comment by gkoz** [comment]
Yes, unfortunately rustc is not smart enough in this case: while `extern fn() {source::trampoline}` coerces to `extern fn()` and `extern fn()` coerces to `unsafe extern fn()`, it can't make the transitive jump. It might accept 
```rust
let trampoline: extern fn(gpointer) = trampoline;
g_idle_add_full(..., Some(trampoline), ...)
```

**Comment by EPashkin** [comment]
Yes it accept it with `let trampoline: extern fn(gpointer) -> gboolean = trampoline;`

**Comment by EPashkin** [comment]
`Some(trampoline as extern fn(gpointer) -> gboolean)` will do too.
And `Some(trampoline as extern fn (_) -> _)`. Not sure that works with multiple params.

**Comment by gkoz** [comment]
Yeah looks like `as` isn't a dangerous cast in this form, just invokes a coercion.

**Comment by EPashkin** [comment]
So what variant use in glib?
In gtk I still prefer use `transform(trampoline as usize)` until generated is done as too many functions here.

**Comment by EPashkin** [comment]
```
extern "C" fn trampoline(func: gpointer) -> gboolean {
    let _guard = CallbackGuard::new();
    unsafe {
        let func: &RefCell<Box<FnMut() -> Continue + 'static>> = transmute(func);
        (&mut *func.borrow_mut())().to_glib()
    }
}

pub fn idle_add<F>(func: F) -> u32
where F: FnMut() -> Continue + Send + 'static {
    unsafe {
        glib_ffi::g_idle_add_full(glib_ffi::G_PRIORITY_DEFAULT_IDLE, Some(trampoline as extern fn (_) -> _),
            into_raw(func), Some(destroy_closure))
    }
}
```
or
```
unsafe extern "C" fn trampoline(func: gpointer) -> gboolean {
    let _guard = CallbackGuard::new();
    let func: &RefCell<Box<FnMut() -> Continue + 'static>> = transmute(func);
    (&mut *func.borrow_mut())().to_glib()
}

pub fn idle_add<F>(func: F) -> u32
where F: FnMut() -> Continue + Send + 'static {
    unsafe {
        glib_ffi::g_idle_add_full(glib_ffi::G_PRIORITY_DEFAULT_IDLE, Some(trampoline),
            into_raw(func), Some(destroy_closure))
    }
}
```
or something other?

**Comment by gkoz** [comment]
I'm happy with both. Personally I'd go for the second style because it's shorter and I don't think having whole `unsafe fn`s makes a difference here.

**Comment by EPashkin** [comment]
Updated.

**Comment by gkoz** [comment]
Thanks!

**Pull request merged**
