### PR TITLE
Add subclassing test for registering signals, action signals, emittin…

### PR DESCRIPTION
**Pull request by sdroege**
…g, signals, etc.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Looks good to me! (Maybe changing the `unwrap` calls?)

**Comment by EPashkin** [comment]
@sdroege Thanks, LGFM

**Comment by sdroege** [comment]
> Maybe changing the `unwrap` calls?

I think those are fine :)

**Comment by GuillaumeGomez** [comment]
I'm just nitpicking considering they are in the test. :)

**Comment by sdroege** [comment]
All green :)

**Comment by GuillaumeGomez** [comment]
All merged! :)

**Pull request merged**
