### PR TITLE
Don't leak the GList/GSList in the from_glib_full_as_vec() impls for …

### PR DESCRIPTION
**Pull request by sdroege**
…them

Fixes https://github.com/gtk-rs/glib/issues/267

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
cc @EPashkin

**Comment by EPashkin** [comment]
@sdroege Thanks
👍

**Comment by sdroege** [comment]
CI is also all happy

**Comment by GuillaumeGomez** [comment]
Then I merge. Thanks!

**Pull request merged**
