### PR TITLE
Implement Send/Sync for more types where it's correct

### PR DESCRIPTION
**Pull request by sdroege**
CC @GuillaumeGomez @EPashkin

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
For such implementations, I'd expect some tests to be sure nothing weird happens.

**Comment by sdroege** [comment]
> For such implementations, I'd expect some tests to be sure nothing weird happens.

There's nothing that can be tested here, that's why it's `unsafe` :)

**Comment by GuillaumeGomez** [comment]
Hum. :-/

**Comment by EPashkin** [comment]
@sdroege Thanks, 👍

**Pull request merged**
