### PR TITLE
Replace unwrap calls with expect in tests

### LINKED ISSUE #592: Use expect() instead of unwrap() in tests
See https://github.com/gtk-rs/glib/pull/589#discussion_r378562349

CC @GuillaumeGomez

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #592.

cc @sdroege @EPashkin

### CODE REVIEW

**Comment by sdroege** [comment]
You didn't update the ones you initially complained about :) See src/subclass/object.rs tests.

**Comment by GuillaumeGomez** [comment]
That was merged after. I'll update the PR shortly.

**Comment by sdroege** [comment]
The tests were already there before that PR :)

**Comment by GuillaumeGomez** [comment]
Then it's cat invasion! :running_man:

**Comment by GuillaumeGomez** [comment]
I think I did all of the ones you added?

**Comment by sdroege** [comment]
Let's merge then. Compared to an `unwrap()` these messages don't bring myself much additional information but you seem to care :)

**Comment by GuillaumeGomez** [comment]
It helps a bit from my point of view so I do care. :)

**Pull request merged**
