### PR TITLE
Format code with rustfmt

### PR DESCRIPTION
**Pull request by sdroege**
@GuillaumeGomez you mentioned a rustfmt config you prefer over the default. Can you provide that one so it can be integrated here?

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
That's something @alatiera might have. :)

**Comment by alatiera** [comment]
> That's something @alatiera might have. :)

What I have in my local checkout is the following:

```sh
➜  gir ✗ cat rustfmt.toml 
indent_style = "Visual"
```

**Comment by sdroege** [comment]
@alatiera said it was

```toml
indent_style = "Visual"
```

Unfortunately configuration in rustfmt is still unstable

```
Warning: can't set `indent_style = Visual`, unstable features are only available in nightly channel.
```

So either we go with the default for now, or more waiting.

**Comment by sdroege** [comment]
@GuillaumeGomez What do you think? Does the formatted code in this PR look fine to you until we can enable that rustfmt configuration, or do you prefer to wait (in which case we should create an issue to ask for stabilization of the configuration we need: you only require `ident_style`?)?

**Comment by GuillaumeGomez** [comment]
I'm not a big fan but that's just minor stuff so let's go.

**Comment by sdroege** [comment]
Ok, thanks! We can add the configuration at a later time, and in the meantime you could ask for it to be stabilized if it's important enough.

If @EPashkin is also fine with this, let's get this merged then. And then I'll prepare MRs for everything else doing the same.

**Comment by GuillaumeGomez** [comment]
I opened an issue for the feature stabilization: https://github.com/rust-lang/rustfmt/issues/3622

**Comment by EPashkin** [comment]
👍

**Pull request merged**
