### PR TITLE
Crate

### PR DESCRIPTION
**Pull request by GuillaumeGomez**

### CODE REVIEW

**Comment by EPashkin** [comment]
IMHO before this need update version in master branch

**Comment by GuillaumeGomez** [comment]
You should add this into the `release_process.md` file so that master is always a version ahead of crate. So for this one, I think we'll just ignore this and make the PR on master afterwards.

**Comment by EPashkin** [comment]
Ok.
Note that we ignored it on previous release too :( Master not be 2 version apart.

**Comment by EPashkin** [comment]
Also IMHO version need be same and changed in same time.

**Comment by GuillaumeGomez** [comment]
Well, if someone wants to override a version by specifying a git, I think it'll be simpler if master if always a version ahead. But otherwise I don't care much, we have to update the version number everytime anyway.

**Comment by EPashkin** [comment]
👍

**Pull request merged**
