### PR TITLE
Implement DerefMut for class structs too

### PR DESCRIPTION
**Pull request by sdroege**
This is needed for subclassing

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Is it the same as #425?

**Comment by sdroege** [comment]
> Is it the same as #425?

Yeah but more correct (it compiles), and includes some more cleanup

**Comment by sdroege** [comment]
@GuillaumeGomez all green :)

**Comment by GuillaumeGomez** [comment]
Then I merge. Thanks!

**Pull request merged**
