### PR TITLE
Fix unittests on macOS

### PR DESCRIPTION
**Pull request by philn**

### CODE REVIEW

**Comment by sdroege** [comment]
:+1:

**Comment by tmiasko** [comment]
It seems that MacOS was fixed, but now Windows is broken ;-)

```
---- translate::tests::test_paths stdout ----
	thread 'translate::tests::test_paths' panicked at 'assertion failed: `(left == right)`
  left: `Some("C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\glib-test.cdycPQvPjmiL")`,
 right: `Some("\\\\?\\C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\glib-test.cdycPQvPjmiL")`', src\translate.rs:1521:9
```

From https://ci.appveyor.com/project/GuillaumeGomez/glib-l2j1a/build/1.0.655/job/9ma7ne925oh991a5

**Comment by GuillaumeGomez** [comment]
Wuuuuuuuuuut

**Comment by tmiasko** [comment]
Let me retest that, I am not sure I was rebased properly. (Job is "running" at https://ci.appveyor.com/project/GuillaumeGomez/glib/build/1.0.651)

**Comment by sdroege** [comment]
Ah nice. For some context:

commit 5624c9d41beba25d8b71c6cbd1b850edbc1d5bfb
Author: Sebastian Dröge <sebastian@centricular.com>
Date:   Tue Dec 5 17:01:07 2017 +0200

    Handle "long path" paths starting with "\\?\" on Windows correctly
    
    On Windows, paths can have \\?\ prepended for long-path support. See
    the MSDN documentation about CreateFile, for example
    
    We have to get rid of this and let GLib take care of all these
    weirdnesses later

**Comment by philn** [comment]
Sorry :)

**Pull request merged**
