### PR TITLE
Add functions to get paramspec name quark and type name quark

### PR DESCRIPTION
**Pull request by sdroege**

### CODE REVIEW

**Comment by sdroege** [comment]
And I need the `Debug` impl to be able to use the new quark stuff in GStreamer :)

**Comment by GuillaumeGomez** [comment]
More implementations makes API easier to use so big :+1: for me!

**Comment by sdroege** [comment]
@GuillaumeGomez all green :)

**Comment by GuillaumeGomez** [comment]
All merged. :)

**Pull request merged**
