### PR TITLE
0.9.1 bugfix release

### PR DESCRIPTION
**Pull request by sdroege**
A couple of cherry-picked commits without further changes. The important one is obviously the last one fixing a crash :)

@EPashkin @GuillaumeGomez

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
For the version update: can you make a PR to master with the version change and then cherry-pick it here please?

**Comment by sdroege** [comment]
> For the version update: can you make a PR to master with the version change and then cherry-pick it here please?

Sure, I assumed your script is doing that but can do :)

**Comment by sdroege** [comment]
https://github.com/gtk-rs/glib/pull/572 . Will cherry-pick in here once merged.

**Comment by sdroege** [comment]
@GuillaumeGomez I don't understand the CI failure here, any guesses? Happens only when building the examples?!

**Comment by GuillaumeGomez** [comment]
Why are the examples complaining about the version? O.o

**Comment by sdroege** [comment]
I think there are two versions of glib-sys here pulled in here somehow. One via the way how you've set up the examples build (which I don't understand), and the other via the crate dependencies as usual. How/to what does the examples build override the glib-sys dependency?

**Comment by GuillaumeGomez** [comment]
I didn't work on this part so I'll need to check. Unless @EPashkin knows already?

**Comment by GuillaumeGomez** [comment]
Looks good to me (but I guess examples will fail).

**Comment by EPashkin** [comment]
Examples will fail as it works with `pending` branch only :(
`git clone -q --depth 50 -b pending https://github.com/gtk-rs/examples _examples`

**Comment by EPashkin** [comment]
@sdroege Thanks, 👍

**Comment by sdroege** [comment]
> Examples will fail as it works with `pending` branch only :(

If we change travis.yml to master instead of pending, would that then work or are there other problems then?

**Comment by EPashkin** [comment]
Gtk use  `-b master ` since gtk-rs/gtk#490 and its seems works

**Comment by sdroege** [comment]
Well, let's try then!

**Comment by GuillaumeGomez** [comment]
For the last commit, if it works, please put it on the crate branch as well afterwards.

**Comment by sdroege** [comment]
First waiting also for https://github.com/gtk-rs/glib/pull/559#issuecomment-573101646

**Comment by sdroege** [comment]
Ah the macos issue here too. Worst platform ever

**Pull request merged**
