### PR TITLE
Regen

### PR DESCRIPTION
**Pull request by EPashkin**
Final part of https://github.com/gtk-rs/sys/issues/82
also contains string constants generation

cc @GuillaumeGomez 
@sdroege please check changes in `source.rs`:
`Pid` made non Copy/Clone.
Also no to_glib/from_glib functions.

~Don't builds until https://github.com/gtk-rs/sys/pull/81 merged~

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Seems good to me.

**Comment by EPashkin** [comment]
I was lucky and this PR actually don't depends on gtk-rs/sys#82 (CI passed without it)
So only need @sdroege confirmation of https://github.com/gtk-rs/glib/pull/296/commits/684936d37700c1ca385628e70748c1e57865125a before PR counts as ready to merge.

**Comment by sdroege** [comment]
:+1:

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
