### PR TITLE
boxed, shared, object: impl FromGlibPtrNone for const

### PR DESCRIPTION
**Pull request by MathieuDuponchelle**

### CODE REVIEW

**Comment by sdroege** [comment]
👍

**Comment by GuillaumeGomez** [comment]
Thanks! Just waiting for CI and I merge (unless @EPashkin finds something wrong).

**Comment by sdroege** [comment]
Ah, pango has some manual implementations of that trait...

**Comment by EPashkin** [comment]
@GuillaumeGomez  👍 It normal that build fails
@MathieuDuponchelle https://github.com/gtk-rs/pango will need fix after this merged.

**Comment by GuillaumeGomez** [comment]
I merge then!

**Comment by MathieuDuponchelle** [comment]
Thanks!

**Pull request merged**
