### PR TITLE
Implement Value::transform()

### PR DESCRIPTION
**Pull request by sdroege**
And some minor fixes.

### CODE REVIEW

**Comment by EPashkin** [comment]
@sdroege Thanks

**Comment by sdroege** [comment]
Hrm

```
(process:7505): GLib-CRITICAL **: source_remove_from_context: assertion 'source_list != NULL' failed

thread '<unnamed>' panicked at 'Receiver without channel', src/libcore/option.rs:1190:5

test main_context_channel::tests::test_sync_channel ... FAILED
```

Unrelated to this change but should be investigated. Putting that on my list and merging.

**Comment by sdroege** [comment]
reproduced here after running the tests in a loop for about 2 hours... ugly :)

**Comment by sdroege** [comment]
This is https://gitlab.gnome.org/GNOME/glib/merge_requests/675#note_589306 . Needs new API in GLib for fixing it reliable, which I'm going to work on in the next days but of course means that we won't have this working reliable until GLib 2.64 at least.

Nothing we can do about that here.

**Comment by EPashkin** [comment]
@sdroege Thanks for look at this issue

**Pull request merged**
