### PR TITLE
Use crates in master, update versions

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/examples/pull/112

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
I'm not sure to understand the point of this PR:

 - We won't update crates' version every time we merge a PR in sys crates.
 - It won't test new changes from sys crates.

Isn't it a bad things going this way?

**Comment by EPashkin** [comment]
- due "^0.3.3" glib uses latest crate up to (but not including) 0.4.0 [see](http://doc.crates.io/specifying-dependencies.html#caret-requirements)
- glib build examples pending branch to test and it contains replacement to git version

**Comment by GuillaumeGomez** [comment]
Hum, ok. Should we make a new release as well (on crates.io)?

**Comment by EPashkin** [comment]
IMHO better wait until you done with `IsA` and do release as planned.
This way we testing that this method really works :wink:

**Comment by GuillaumeGomez** [comment]
Ok! When you thing everythings ok, just ping me on every PR then (won't have much time today) and I'll try to merge them quickly.

**Comment by EPashkin** [comment]
Can you go to end of https://github.com/gtk-rs/examples/pull/112 and merge it by references?

**Comment by GuillaumeGomez** [comment]
Let's do it then!

**Pull request merged**
