### PR TITLE
Add version for Sha384

### PR DESCRIPTION
**Pull request by EPashkin**
See https://github.com/gtk-rs/glib/pull/226#discussion_r136460029

@GuillaumeGomez, @sdroege

### CODE REVIEW

**Comment by EPashkin** [comment]
`glib\gchecksum.h` says `@G_CHECKSUM_SHA384: Use the SHA-384 hashing algorithm (Since: 2.51)`,
but as I remember, gtk used even published version

**Comment by GuillaumeGomez** [comment]
So what should we do about it?

**Comment by EPashkin** [comment]
Nothing if gtk publish policy not changed.

**Comment by GuillaumeGomez** [comment]
I'll have to make a new release way more early than expected.

**Comment by EPashkin** [comment]
But not too early :wink:, all other crates also need update features, I forgot about it.

**Comment by sdroege** [comment]
> I'll have to make a new release way more early than expected.

Why? This was just added with the last PR and is not in the release :)

> Nothing if gtk publish policy not changed.

It didn't, you can put 2.52 there

**Comment by EPashkin** [comment]
@GuillaumeGomez, then this ready to merge.
About updating features in other crates: I will add PRs or better wait until you publish crates with `GtkWindow`-fix?

**Comment by GuillaumeGomez** [comment]
Since it's another "major" release, I'll wait a few weeks at least.

**Pull request merged**
