### PR TITLE
Fix array of string full transfer

### PR DESCRIPTION
**Pull request by EPashkin**
Fix https://github.com/gtk-rs/gtk/issues/469

@Susurrus check this please.

### CODE REVIEW

**Comment by EPashkin** [comment]
@GuillaumeGomez, please look https://github.com/gtk-rs/glib/blob/master/src/translate.rs#L1017-L1019
and https://github.com/gtk-rs/glib/blob/master/src/translate.rs#L1077-L1079
I'm wrong or no way condition will be false?

**Comment by GuillaumeGomez** [comment]
Well:

```rust
if num == 0 || ptr.is_null() {
    return Vec::new()
}
```

So impossible to be null, indeed.

**Comment by EPashkin** [comment]
Fixed

**Comment by GuillaumeGomez** [comment]
Thanks!

**Comment by EPashkin** [comment]
Strange, appveyour do 2 builds per "action".

**Comment by GuillaumeGomez** [comment]
Travis too some times. Dark magic and stuff.

**Comment by Susurrus** [comment]
Looks like this fixed my code example. Thanks!

**Pull request merged**
