### PR TITLE
Fix Char tests on platforms where c_char is u8 instead of i8

### PR DESCRIPTION
**Pull request by sdroege**
Also add correct casts to the UChar tests while we're at it.

Fixes https://github.com/gtk-rs/glib/issues/284

### CODE REVIEW

**Comment by EPashkin** [comment]
@sdroege Thanks

**Comment by ignatenkobrain** [comment]
Let me try this on our altarches

**Comment by ignatenkobrain** [comment]
This works just fine ;)

**Comment by sdroege** [comment]
What architecture is that btw? PPC?

**Comment by ignatenkobrain** [comment]
ppc64, ppc64le, s390x, aarch64, armv7hl

**Comment by sdroege** [comment]
I didn't know armv7hl and aarch64 also had unsigned chars by default

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
