### PR TITLE
Use functions, ending with _utf8 under Windows

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/gir/issues/375

### CODE REVIEW

**Comment by EPashkin** [comment]
@GuillaumeGomez, @sdroege I need you option:
1) MSYS2 `mingw64/mingw-w64-x86_64-glib2 2.52.2-1` don't have _utf8 version for 4 functions
```
d:\eap\rust\0\./target\debug\deps\glib-69e7bba60aa93509.glib-utils.o: In function `glib::utils::get_user_name':
d:\eap\rust\0\glib/src/utils.rs:81: undefined reference to `g_get_user_name_utf8'
d:\eap\rust\0\./target\debug\deps\glib-69e7bba60aa93509.glib-utils.o: In function `glib::utils::get_real_name':
d:\eap\rust\0\glib/src/utils.rs:92: undefined reference to `g_get_real_name_utf8'
d:\eap\rust\0\./target\debug\deps\glib-69e7bba60aa93509.glib-utils.o: In function `glib::utils::get_home_dir':
d:\eap\rust\0\glib/src/utils.rs:141: undefined reference to `g_get_home_dir_utf8'
d:\eap\rust\0\./target\debug\deps\glib-69e7bba60aa93509.glib-utils.o: In function `glib::utils::get_tmp_dir':
d:\eap\rust\0\glib/src/utils.rs:152: undefined reference to `g_get_tmp_dir_utf8'
```
same with g_find_program_in_path but it don't fails on lib test, only on usage attempt.

By https://github.com/GNOME/glib/blob/master/glib/gutils.c#L2315 these function don't have suffix on win64 (and only these in glib)
So I used `#[cfg(all(windows,target_arch="x86"))]` and `#[cfg(not(all(windows,target_arch="x86")))]`

**Comment by EPashkin** [comment]
2) I reexported utils::* and hide mod utils

**Comment by EPashkin** [comment]
@GuillaumeGomez please look at this

**Comment by GuillaumeGomez** [comment]
Awesome, thanks!

**Pull request merged**
