### PR TITLE
Various GObject property changes

### PR DESCRIPTION
**Pull request by sdroege**

### CODE REVIEW

**Comment by EPashkin** [comment]
👍, thought it currently not works with enums.

**Comment by sdroege** [comment]
> thought it currently not works with enums.

Correct unfortunately: https://github.com/gtk-rs/glib/issues/187

My plan here is to get rid of the generic trait impls for all the conversion traits and get them via macros, and then we get GValue support for boxed types, enums, etc automatically with some additional effort.

**Comment by sdroege** [comment]
@GuillaumeGomez Let's get this in then? :)

**Comment by GuillaumeGomez** [comment]
Indeed! (Started to look at it but forgot meantime...)

Thanks!

**Pull request merged**
