### PR TITLE
Directly access the GType in the GValue instead of doing raw pointer …

### PR DESCRIPTION
**Pull request by sdroege**
…casting

Depends on https://github.com/gtk-rs/sys/pull/46 and https://github.com/gtk-rs/gir/pull/341

### CODE REVIEW

**Comment by sdroege** [comment]
This should apply and work now

**Comment by EPashkin** [comment]
@GuillaumeGomez Please restrart CI for this.

**Comment by GuillaumeGomez** [comment]
Yes sir!

**Comment by EPashkin** [comment]
CI passed

**Comment by GuillaumeGomez** [comment]
Thanks @sdroege!

**Pull request merged**
