### PR TITLE
Gir files zesty

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/gir-files/issues/1

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Is it normal that the submodule reference isn't working in travis?

**Comment by EPashkin** [comment]
Yes normal, it still not merged https://github.com/gtk-rs/gir-files/issues/2

**Comment by GuillaumeGomez** [comment]
Ok, now it's all good!

**Comment by EPashkin** [comment]
@GuillaumeGomez, dependent PRs better don't merge if you don't want publish all `gtk-rs` crate,
as currently its use more features.

**Comment by EPashkin** [comment]
.. and I currently don't see way to build crates dependent on unpublished feature

**Comment by EPashkin** [comment]
Oops, forgot that it just "Test PR",

**Comment by EPashkin** [comment]
.. to do normal I need update `gir-files` and do full regen.
Previous comment apply to final version.

**Pull request merged**
