### PR TITLE
Replace unwrap calls with "more explicit" expect

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Part of https://github.com/gtk-rs/gtk/issues/743.

cc @sdroege @EPashkin

### CODE REVIEW

**Comment by EPashkin** [comment]
@GuillaumeGomez  Thanks, 👍

**Comment by sdroege** [comment]
Instead of "invalid string" you could also be more specific as this *only* happens if there's a "\0" somewhere in the string before the end. Otherwise seems fine to me

**Comment by GuillaumeGomez** [comment]
Are you sure this is the only case where it could fail?

**Comment by sdroege** [comment]
Yes: https://doc.rust-lang.org/std/ffi/struct.CString.html#method.new

It's part of the API, it can't possibly fail for anything but a `NulError`:
```rust
pub fn new<T: Into<Vec<u8>>>(t: T) -> Result<CString, NulError>
```

**Comment by GuillaumeGomez** [comment]
Ok then! I'll update the sentence when I can.

**Comment by GuillaumeGomez** [comment]
Updated.

**Comment by sdroege** [comment]
:+1:

**Pull request merged**
