### PR TITLE
Improve set/get_property validity checks and allow to set properties from values that are a subtype of the property type

### PR DESCRIPTION
**Pull request by sdroege**
See https://github.com/gtk-rs/glib/pull/308, extends that PR.

@tmiasko @GuillaumeGomez

### CODE REVIEW

**Comment by sdroege** [comment]
I can't find any property where this could easily be tested. Anybody knows one?

**Comment by GuillaumeGomez** [comment]
Nothing's coming to my mind...

**Comment by sdroege** [comment]
Ah in GStreamer, giostreamsrc for examples takes `GInputStream` on the `stream` property.

**Comment by sdroege** [comment]
Works in GStreamer btw, should be good to go then

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
