### PR TITLE
signal: Make SignalHandlerId derive from Clone

### PR DESCRIPTION
**Pull request by philn**
I think this would be useful :)

### CODE REVIEW

**Comment by EPashkin** [comment]
As I remember @sdroege specially don't derive `Clone` to prevent double disconnecting

**Comment by philn** [comment]
Huh... ok... so how would I block a signal handler from 2 different closures?

**Comment by EPashkin** [comment]
Use `Rc<Cell<>>`?

**Comment by philn** [comment]
I already tried with a `RefCell` but it's captured by the first closure.

**Comment by EPashkin** [comment]
Strange, normally, you `clone` RC before moving into closures, so only "half" captured.

**Comment by philn** [comment]
Ah well, I got it working finally with some `Arc<Mutex<>>` trickery :)

**Comment by EPashkin** [comment]
Do not forget to close this PR if problem solved 😉

**Comment by sdroege** [comment]
Yes, the id should be unique so you only can ever remove it once

**Pull request closed without merging**
