### PR TITLE
Implement StaticType and GValue traits for boxed/shared types too

### PR DESCRIPTION
**Pull request by sdroege**
As long as a get_type() function is provided to the macro.

### CODE REVIEW

**Comment by sdroege** [comment]
This should be ready too now, and is needed for gtk-rs/gir#410

CI is unhappy though, which looks like out of memory or timeouts... before this PR already.

**Comment by GuillaumeGomez** [comment]
Restarted CI.

**Comment by EPashkin** [comment]
Value impls for enums and flags don't have #cfg (see `GdkGLError`  and `GdkAxisFlags`)

**Comment by EPashkin** [comment]
@GuillaumeGomez 👍 for merge this PR despite CI internal problem
@sdroege, thanks.

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
