### PR TITLE
Run futures code and tests when building with nightly

### PR DESCRIPTION
**Pull request by sdroege**

### CODE REVIEW

**Comment by EPashkin** [comment]
Seems this need be after examples

**Comment by sdroege** [comment]
No, this fails for other reasons. Will investigate.

The examples might still fail until all PRs are merged though.

**Comment by sdroege** [comment]
Yeah, silly :) Because it was stabilized now I need to remove the `#![feature]` thingy.

**Comment by GuillaumeGomez** [comment]
It builds but fails because examples don't have `futures` feature.

**Comment by sdroege** [comment]
Yeah, I misread. So this is fine and we need to go through the crates one by one as usual and do the examples as the last one.

**Comment by sdroege** [comment]
Once https://github.com/gtk-rs/examples/pull/240 is in, this one here should also succeed.

**Comment by sdroege** [comment]
@GuillaumeGomez travis is green :)

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
