### PR TITLE
Implement ObjectExt::emit() for emitting arbitrary signals

### PR DESCRIPTION
**Pull request by sdroege**
Depends on, and includes, https://github.com/gtk-rs/glib/pull/191

### CODE REVIEW

**Comment by sdroege** [comment]
Before you ask, this is mostly useful for G_SIGNAL_ACTION signals. E.g. GtkWindow's activate-focus signal.

Action signals are basically function calls. They are emitted/called from the outside on the object, and the object handles them internally.

**Comment by sdroege** [comment]
And updated so that it only includes the relevant commit here now

**Comment by EPashkin** [comment]
👍 Thanks again

**Comment by GuillaumeGomez** [comment]
Thanks! Waiting for CIs.

**Comment by GuillaumeGomez** [comment]
Indeed. :)

**Pull request merged**
