### PR TITLE
Update to futures 0.3

### PR DESCRIPTION
**Pull request by sdroege**
And require Rust 1.39.

We can't use async/await in the tests/etc yet because that requires
switching to the 2018 edition, and that is blocked by
https://github.com/gtk-rs/gir/issues/746

### CODE REVIEW

**Comment by EPashkin** [comment]
@sdroege Thanks.
Maybe better leave empty "futures" trait until we process all other crates?
https://travis-ci.org/gtk-rs/glib/jobs/610219157#L670

**Comment by sdroege** [comment]
>  Maybe better leave empty "futures" trait until we process all other crates?

feature you mean? That would mean that we have to update everything twice :)

**Comment by sdroege** [comment]
@GuillaumeGomez Btw, we'll have to regen everything for this. gir PR coming soon

**Comment by GuillaumeGomez** [comment]
Looks good to me! Waiting for CI.

**Comment by sdroege** [comment]
> Looks good to me! Waiting for CI.

CI will fail until we updated all the things :)

**Comment by GuillaumeGomez** [comment]
Ah.

**Comment by EPashkin** [comment]
@sdroege you seems forgot to remove `FEATURES=futures` from travis

**Pull request merged**
