### PR TITLE
OsString support and regen

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/gir/issues/592

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
If it's just a wrapper above the C utils, there is no point to bind it since Rust has its own methods to interact with environment. I think you took the good decision by removing this (useless) step.

**Comment by sdroege** [comment]
Yes, remove

**Comment by EPashkin** [comment]
Updated

**Comment by tmiasko** [comment]
Is there any reason for having functions designed to work with environment,
g_get_environ, g_listenv, g_unsetenv, g_getenv, etc., exposed in Rust?
Especially that Rust ones are a little bit more thread-safe, i.e.,
they are synchronized internally.

**Comment by GuillaumeGomez** [comment]
No, thqt's why we said that he'd better remove them.

**Comment by tmiasko** [comment]
Those in Gio.AppLaunchContext and ApplicationCommandLine are useful and without direct Rust replacement.

**Comment by EPashkin** [comment]
@GuillaumeGomez Travis single failure related to futures error, @sdroege already send PR.

**Comment by GuillaumeGomez** [comment]
Let's merge then. Thanks!

**Pull request merged**
